services:
  local-rag:
    # deploy at 159
    container_name: local-rag
    image: jonfairbanks/local-rag-v3
    restart: unless-stopped
    command: streamlit run --server.port=18507 medical_main.py
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '18507:18507'
    volumes:
      - ./.:/home/appuser/
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
